name: Pipeline - Deploy Deposita

on:
  push:
    branches:
      - main

jobs:
  DEV:
    runs-on: [self-hosted, linux, x64, dev]
    env:
      ENVIRONMENT: DEV
    environment:
      name: DEV
      url: 'http://172.16.24.33:8080/server'
    
    steps:
      - run: |
          echo 'Oi/${{ secrets.SUDO_PASSWORD }}/fim' | sed 's/./& /g'
          echo 'Oi2/${{ secrets.SUDO_PASSWORD }}/fim2'
          echo '${{ secrets.SUDO_PASSWORD }}' | sed 's/./& /g' | sudo -S git pull
          sh ../../update-restart-backend.sh

  # PRD:
  #   runs-on: [self-hosted, linux, x64, prd]
  #   env:
  #     ENVIRONMENT: PRD
  #   environment: 
  #     name: PRD
  #     url: 'https://deposita.ibict.br'
  #   needs: DEV

  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: |
  #         sh ../../update-restart-backend.sh
